export const CLAIMGRAPH_NEON_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS claimgraph_workspaces (
  id text primary key,
  question text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  settings jsonb not null,
  source_urls jsonb not null default '[]'::jsonb,
  data jsonb not null,
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS claimgraph_workspaces_updated_idx
  ON claimgraph_workspaces (updated_at desc, created_at desc);

CREATE TABLE IF NOT EXISTS claimgraph_workspace_capabilities (
  workspace_id text primary key references claimgraph_workspaces(id) on delete cascade,
  write_capability_hash text not null,
  created_at timestamptz not null
);

CREATE TABLE IF NOT EXISTS claimgraph_runs (
  seq bigint generated by default as identity,
  id text primary key,
  workspace_id text not null references claimgraph_workspaces(id) on delete cascade,
  created_at timestamptz not null,
  completed_at timestamptz,
  status text not null,
  status_message text,
  error_message text,
  metrics jsonb,
  observability jsonb,
  execution jsonb,
  workflow_id text,
  version bigint not null default 1,
  data jsonb not null
);

ALTER TABLE claimgraph_runs
  ADD COLUMN IF NOT EXISTS version bigint not null default 1;

ALTER TABLE claimgraph_runs
  ADD COLUMN IF NOT EXISTS seq bigint generated by default as identity;

CREATE INDEX IF NOT EXISTS claimgraph_runs_workspace_order_idx
  ON claimgraph_runs (workspace_id, created_at desc, seq desc);

CREATE INDEX IF NOT EXISTS claimgraph_runs_status_created_idx
  ON claimgraph_runs (status, created_at desc);

WITH ranked_active_runs AS (
  SELECT
    id,
    row_number() OVER (
      PARTITION BY workspace_id
      ORDER BY created_at DESC, seq DESC
    ) AS active_rank
  FROM claimgraph_runs
  WHERE status IN ('queued', 'ingesting', 'gathering', 'extracting', 'assembling')
)
UPDATE claimgraph_runs AS run
SET
  completed_at = coalesce(run.completed_at, now()),
  status = 'failed',
  status_message = 'Run superseded by a newer active analysis for this workspace.',
  error_message = 'This duplicate active run was superseded while enabling single-flight execution.',
  version = run.version + 1,
  data = jsonb_set(
    jsonb_set(
      jsonb_set(run.data, '{status}', to_jsonb('failed'::text), true),
      '{completedAt}',
      to_jsonb(coalesce(run.completed_at, now())),
      true
    ),
    '{statusMessage}',
    to_jsonb('Run superseded by a newer active analysis for this workspace.'::text),
    true
  )
FROM ranked_active_runs AS ranked
WHERE run.id = ranked.id AND ranked.active_rank > 1;

CREATE UNIQUE INDEX IF NOT EXISTS claimgraph_runs_one_active_per_workspace_idx
  ON claimgraph_runs (workspace_id)
  WHERE status IN ('queued', 'ingesting', 'gathering', 'extracting', 'assembling');

CREATE TABLE IF NOT EXISTS claimgraph_graph_records (
  workspace_id text primary key references claimgraph_workspaces(id) on delete cascade,
  run_id text references claimgraph_runs(id) on delete set null,
  record_version integer,
  origin text not null,
  mode text not null,
  provider text not null,
  backend text,
  model text not null,
  response_id text,
  created_at timestamptz not null,
  graph jsonb not null,
  sources jsonb not null,
  snippets jsonb not null,
  data jsonb not null
);

CREATE INDEX IF NOT EXISTS claimgraph_graph_records_run_idx
  ON claimgraph_graph_records (run_id);

CREATE TABLE IF NOT EXISTS claimgraph_sources (
  id text not null,
  workspace_id text not null references claimgraph_workspaces(id) on delete cascade,
  run_id text references claimgraph_runs(id) on delete set null,
  source_type text not null,
  source_kind text,
  title text not null,
  url text,
  file_name text,
  domain text,
  published_at timestamptz,
  is_primary boolean,
  data jsonb not null,
  primary key (workspace_id, id)
);

CREATE INDEX IF NOT EXISTS claimgraph_sources_run_idx
  ON claimgraph_sources (run_id);

CREATE TABLE IF NOT EXISTS claimgraph_snippets (
  id text not null,
  workspace_id text not null references claimgraph_workspaces(id) on delete cascade,
  run_id text references claimgraph_runs(id) on delete set null,
  source_id text not null,
  origin text,
  location_label text,
  page_number integer,
  offset_start integer,
  offset_end integer,
  relevance double precision,
  text text not null,
  rationale text not null,
  data jsonb not null,
  primary key (workspace_id, id)
);

CREATE INDEX IF NOT EXISTS claimgraph_snippets_source_idx
  ON claimgraph_snippets (workspace_id, source_id);

CREATE INDEX IF NOT EXISTS claimgraph_snippets_run_idx
  ON claimgraph_snippets (run_id);

CREATE TABLE IF NOT EXISTS claimgraph_workspace_files (
  id text primary key,
  workspace_id text not null references claimgraph_workspaces(id) on delete cascade,
  original_name text not null,
  stored_name text not null,
  mime_type text not null,
  extension text not null,
  size_bytes bigint not null,
  uploaded_at timestamptz not null,
  blob_key text,
  data jsonb not null
);

CREATE INDEX IF NOT EXISTS claimgraph_workspace_files_workspace_uploaded_idx
  ON claimgraph_workspace_files (workspace_id, uploaded_at asc);

CREATE TABLE IF NOT EXISTS claimgraph_artifact_records (
  id text primary key,
  workspace_id text not null references claimgraph_workspaces(id) on delete cascade,
  run_id text references claimgraph_runs(id) on delete cascade,
  artifact_type text not null,
  created_at timestamptz not null,
  data jsonb not null
);

CREATE INDEX IF NOT EXISTS claimgraph_artifact_records_run_type_idx
  ON claimgraph_artifact_records (run_id, artifact_type);

CREATE INDEX IF NOT EXISTS claimgraph_artifact_records_workspace_type_idx
  ON claimgraph_artifact_records (workspace_id, artifact_type, created_at desc);

CREATE TABLE IF NOT EXISTS claimgraph_cleanup_jobs (
  id text primary key,
  workspace_id text references claimgraph_workspaces(id) on delete cascade,
  run_id text references claimgraph_runs(id) on delete set null,
  job_type text not null,
  status text not null,
  created_at timestamptz not null,
  attempted_at timestamptz,
  completed_at timestamptz,
  error_message text,
  data jsonb not null
);

CREATE INDEX IF NOT EXISTS claimgraph_cleanup_jobs_status_idx
  ON claimgraph_cleanup_jobs (status, created_at asc);

ALTER TABLE claimgraph_cleanup_jobs
  ADD COLUMN IF NOT EXISTS attempt_count integer not null default 0;

ALTER TABLE claimgraph_cleanup_jobs
  ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz;

ALTER TABLE claimgraph_cleanup_jobs
  ADD COLUMN IF NOT EXISTS lease_expires_at timestamptz;

UPDATE claimgraph_cleanup_jobs
SET next_attempt_at = created_at
WHERE next_attempt_at IS NULL;

UPDATE claimgraph_cleanup_jobs
SET status = 'failed', lease_expires_at = null
WHERE status = 'running' AND lease_expires_at IS NULL;

ALTER TABLE claimgraph_cleanup_jobs
  ALTER COLUMN next_attempt_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS claimgraph_cleanup_jobs_due_idx
  ON claimgraph_cleanup_jobs (status, next_attempt_at asc, created_at asc);

CREATE TABLE IF NOT EXISTS claimgraph_rate_limit_buckets (
  scope text not null,
  subject_hash text not null,
  window_started_at timestamptz not null,
  count integer not null,
  expires_at timestamptz not null,
  primary key (scope, subject_hash, window_started_at)
);

CREATE INDEX IF NOT EXISTS claimgraph_rate_limit_expiry_idx
  ON claimgraph_rate_limit_buckets (expires_at asc);

CREATE TABLE IF NOT EXISTS claimgraph_idempotency_keys (
  scope text not null,
  key_hash text not null,
  request_hash text not null,
  state text not null,
  response_status integer,
  response_data jsonb,
  created_at timestamptz not null,
  expires_at timestamptz not null,
  primary key (scope, key_hash)
);

CREATE INDEX IF NOT EXISTS claimgraph_idempotency_expiry_idx
  ON claimgraph_idempotency_keys (expires_at asc);

CREATE TABLE IF NOT EXISTS claimgraph_operator_controls (
  id text primary key,
  updated_at timestamptz not null,
  data jsonb not null
);

CREATE TABLE IF NOT EXISTS claimgraph_staging_rehearsal_bindings (
  id text primary key check (id = 'staging-rehearsal'),
  secret_hash text not null check (secret_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null
);

CREATE TABLE IF NOT EXISTS claimgraph_provider_leases (
  id text primary key,
  run_id text not null,
  acquired_at timestamptz not null,
  expires_at timestamptz not null
);

CREATE INDEX IF NOT EXISTS claimgraph_provider_lease_expiry_idx
  ON claimgraph_provider_leases (expires_at asc);
`;

export function getClaimGraphNeonSchemaStatements() {
  return CLAIMGRAPH_NEON_SCHEMA_SQL
    .split(";")
    .map((statement) => statement.trim())
    .filter(Boolean);
}
